### ISSUE TITLE
Blazor WASM: Error loading library

### ISSUE THREAD

**Issue by filipelteixeira** [AspNetMonsters/Blazor.Geolocation#15]
I've added Blazor.Geolocation as described in the readme file.
However when I run the application the following error pops-up:
`blazor.webassembly.js:1 WASM: ﻿Unhandled exception rendering component:
l.printErr @ blazor.webassembly.js:1
put_char @ dotnet.js:1
write @ dotnet.js:1
write @ dotnet.js:1
___syscall4 @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_wasm_invoke_method @ dotnet.js:1
call_method @ dotnet.js:1
(anonymous) @ dotnet.js:1
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
_mono_wasm_invoke_js_marshalled @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_wasm_invoke_method @ dotnet.js:1
call_method @ dotnet.js:1
set_task_result @ dotnet.js:1
(anonymous) @ dotnet.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.js:1
_mono_wasm_invoke_js_with_args @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_background_exec @ dotnet.js:1
pump_message @ dotnet.js:1
blazor.webassembly.js:1 WASM: Microsoft.JSInterop.JSException: Could not find 'AspNetMonsters' in 'window'.
l.printErr @ blazor.webassembly.js:1
put_char @ dotnet.js:1
write @ dotnet.js:1
write @ dotnet.js:1
___syscall4 @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_wasm_invoke_method @ dotnet.js:1
call_method @ dotnet.js:1
(anonymous) @ dotnet.js:1
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
_mono_wasm_invoke_js_marshalled @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_wasm_invoke_method @ dotnet.js:1
call_method @ dotnet.js:1
set_task_result @ dotnet.js:1
(anonymous) @ dotnet.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.js:1
_mono_wasm_invoke_js_with_args @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_background_exec @ dotnet.js:1
pump_message @ dotnet.js:1
blazor.webassembly.js:1 WASM: Error: Could not find 'AspNetMonsters' in 'window'.
l.printErr @ blazor.webassembly.js:1
put_char @ dotnet.js:1
write @ dotnet.js:1
write @ dotnet.js:1
___syscall4 @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_wasm_invoke_method @ dotnet.js:1
call_method @ dotnet.js:1
(anonymous) @ dotnet.js:1
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
_mono_wasm_invoke_js_marshalled @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_wasm_invoke_method @ dotnet.js:1
call_method @ dotnet.js:1
set_task_result @ dotnet.js:1
(anonymous) @ dotnet.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.js:1
_mono_wasm_invoke_js_with_args @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_background_exec @ dotnet.js:1
pump_message @ dotnet.js:1
blazor.webassembly.js:1 WASM:     at https://localhost:44347/_framework/blazor.webassembly.js:1:8937
l.printErr @ blazor.webassembly.js:1
put_char @ dotnet.js:1
write @ dotnet.js:1
write @ dotnet.js:1
___syscall4 @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_wasm_invoke_method @ dotnet.js:1
call_method @ dotnet.js:1
(anonymous) @ dotnet.js:1
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
_mono_wasm_invoke_js_marshalled @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_wasm_invoke_method @ dotnet.js:1
call_method @ dotnet.js:1
set_task_result @ dotnet.js:1
(anonymous) @ dotnet.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.js:1
_mono_wasm_invoke_js_with_args @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_background_exec @ dotnet.js:1
pump_message @ dotnet.js:1
blazor.webassembly.js:1 WASM:     at Array.forEach (<anonymous>)
l.printErr @ blazor.webassembly.js:1
put_char @ dotnet.js:1
write @ dotnet.js:1
write @ dotnet.js:1
___syscall4 @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_wasm_invoke_method @ dotnet.js:1
call_method @ dotnet.js:1
(anonymous) @ dotnet.js:1
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
_mono_wasm_invoke_js_marshalled @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_wasm_invoke_method @ dotnet.js:1
call_method @ dotnet.js:1
set_task_result @ dotnet.js:1
(anonymous) @ dotnet.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.js:1
_mono_wasm_invoke_js_with_args @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_background_exec @ dotnet.js:1
pump_message @ dotnet.js:1
blazor.webassembly.js:1 WASM:     at p (https://localhost:44347/_framework/blazor.webassembly.js:1:8898)
l.printErr @ blazor.webassembly.js:1
put_char @ dotnet.js:1
write @ dotnet.js:1
write @ dotnet.js:1
___syscall4 @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_wasm_invoke_method @ dotnet.js:1
call_method @ dotnet.js:1
(anonymous) @ dotnet.js:1
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
_mono_wasm_invoke_js_marshalled @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_wasm_invoke_method @ dotnet.js:1
call_method @ dotnet.js:1
set_task_result @ dotnet.js:1
(anonymous) @ dotnet.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.js:1
_mono_wasm_invoke_js_with_args @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_background_exec @ dotnet.js:1
pump_message @ dotnet.js:1
blazor.webassembly.js:1 WASM:     at https://localhost:44347/_framework/blazor.webassembly.js:1:9605
l.printErr @ blazor.webassembly.js:1
put_char @ dotnet.js:1
write @ dotnet.js:1
write @ dotnet.js:1
___syscall4 @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_wasm_invoke_method @ dotnet.js:1
call_method @ dotnet.js:1
(anonymous) @ dotnet.js:1
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
_mono_wasm_invoke_js_marshalled @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_wasm_invoke_method @ dotnet.js:1
call_method @ dotnet.js:1
set_task_result @ dotnet.js:1
(anonymous) @ dotnet.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.js:1
_mono_wasm_invoke_js_with_args @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_background_exec @ dotnet.js:1
pump_message @ dotnet.js:1
blazor.webassembly.js:1 WASM:     at new Promise (<anonymous>)
l.printErr @ blazor.webassembly.js:1
put_char @ dotnet.js:1
write @ dotnet.js:1
write @ dotnet.js:1
___syscall4 @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_wasm_invoke_method @ dotnet.js:1
call_method @ dotnet.js:1
(anonymous) @ dotnet.js:1
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
_mono_wasm_invoke_js_marshalled @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_wasm_invoke_method @ dotnet.js:1
call_method @ dotnet.js:1
set_task_result @ dotnet.js:1
(anonymous) @ dotnet.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.js:1
_mono_wasm_invoke_js_with_args @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_background_exec @ dotnet.js:1
pump_message @ dotnet.js:1
blazor.webassembly.js:1 WASM:     at Object.beginInvokeJSFromDotNet (https://localhost:44347/_framework/blazor.webassembly.js:1:9579)
l.printErr @ blazor.webassembly.js:1
put_char @ dotnet.js:1
write @ dotnet.js:1
write @ dotnet.js:1
___syscall4 @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_wasm_invoke_method @ dotnet.js:1
call_method @ dotnet.js:1
(anonymous) @ dotnet.js:1
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
_mono_wasm_invoke_js_marshalled @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_wasm_invoke_method @ dotnet.js:1
call_method @ dotnet.js:1
set_task_result @ dotnet.js:1
(anonymous) @ dotnet.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.js:1
_mono_wasm_invoke_js_with_args @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_background_exec @ dotnet.js:1
pump_message @ dotnet.js:1
blazor.webassembly.js:1 WASM:     at _mono_wasm_invoke_js_marshalled (https://localhost:44347/_framework/wasm/dotnet.js:1:166149)
l.printErr @ blazor.webassembly.js:1
put_char @ dotnet.js:1
write @ dotnet.js:1
write @ dotnet.js:1
___syscall4 @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_wasm_invoke_method @ dotnet.js:1
call_method @ dotnet.js:1
(anonymous) @ dotnet.js:1
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
_mono_wasm_invoke_js_marshalled @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_wasm_invoke_method @ dotnet.js:1
call_method @ dotnet.js:1
set_task_result @ dotnet.js:1
(anonymous) @ dotnet.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.js:1
_mono_wasm_invoke_js_with_args @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_background_exec @ dotnet.js:1
pump_message @ dotnet.js:1
blazor.webassembly.js:1 WASM:     at wasm-function[6199]:0x1187e2
l.printErr @ blazor.webassembly.js:1
put_char @ dotnet.js:1
write @ dotnet.js:1
write @ dotnet.js:1
___syscall4 @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_wasm_invoke_method @ dotnet.js:1
call_method @ dotnet.js:1
(anonymous) @ dotnet.js:1
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
_mono_wasm_invoke_js_marshalled @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_wasm_invoke_method @ dotnet.js:1
call_method @ dotnet.js:1
set_task_result @ dotnet.js:1
(anonymous) @ dotnet.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.js:1
_mono_wasm_invoke_js_with_args @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_background_exec @ dotnet.js:1
pump_message @ dotnet.js:1
blazor.webassembly.js:1 WASM:     at wasm-function[1432]:0x40349
l.printErr @ blazor.webassembly.js:1
put_char @ dotnet.js:1
write @ dotnet.js:1
write @ dotnet.js:1
___syscall4 @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_wasm_invoke_method @ dotnet.js:1
call_method @ dotnet.js:1
(anonymous) @ dotnet.js:1
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
_mono_wasm_invoke_js_marshalled @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_wasm_invoke_method @ dotnet.js:1
call_method @ dotnet.js:1
set_task_result @ dotnet.js:1
(anonymous) @ dotnet.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.js:1
_mono_wasm_invoke_js_with_args @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_background_exec @ dotnet.js:1
pump_message @ dotnet.js:1
blazor.webassembly.js:1 WASM:     at wasm-function[635]:0x146fe
l.printErr @ blazor.webassembly.js:1
put_char @ dotnet.js:1
write @ dotnet.js:1
write @ dotnet.js:1
___syscall4 @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_wasm_invoke_method @ dotnet.js:1
call_method @ dotnet.js:1
(anonymous) @ dotnet.js:1
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
_mono_wasm_invoke_js_marshalled @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_wasm_invoke_method @ dotnet.js:1
call_method @ dotnet.js:1
set_task_result @ dotnet.js:1
(anonymous) @ dotnet.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.js:1
_mono_wasm_invoke_js_with_args @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_background_exec @ dotnet.js:1
pump_message @ dotnet.js:1
blazor.webassembly.js:1 WASM:   at System.Threading.Tasks.ValueTask`1[TResult].get_Result () <0x226d238 + 0x0002c> in <filename unknown>:0 
l.printErr @ blazor.webassembly.js:1
put_char @ dotnet.js:1
write @ dotnet.js:1
write @ dotnet.js:1
___syscall4 @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_wasm_invoke_method @ dotnet.js:1
call_method @ dotnet.js:1
(anonymous) @ dotnet.js:1
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
_mono_wasm_invoke_js_marshalled @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_wasm_invoke_method @ dotnet.js:1
call_method @ dotnet.js:1
set_task_result @ dotnet.js:1
(anonymous) @ dotnet.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.js:1
_mono_wasm_invoke_js_with_args @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_background_exec @ dotnet.js:1
pump_message @ dotnet.js:1
blazor.webassembly.js:1 WASM:   at AspNetMonsters.Blazor.Geolocation.LocationService.GetLocationAsync () <0x2234120 + 0x0013c> in <filename unknown>:0 
l.printErr @ blazor.webassembly.js:1
put_char @ dotnet.js:1
write @ dotnet.js:1
write @ dotnet.js:1
___syscall4 @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_wasm_invoke_method @ dotnet.js:1
call_method @ dotnet.js:1
(anonymous) @ dotnet.js:1
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
_mono_wasm_invoke_js_marshalled @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_wasm_invoke_method @ dotnet.js:1
call_method @ dotnet.js:1
set_task_result @ dotnet.js:1
(anonymous) @ dotnet.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.js:1
_mono_wasm_invoke_js_with_args @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_background_exec @ dotnet.js:1
pump_message @ dotnet.js:1
blazor.webassembly.js:1 WASM:   at dotnet.blazor.webassembly.weatherSA.Pages.Index.OnInitializedAsync () [0x000bc] in C:\Workspace\dotnet\dotnet.blazor.webassembly.weatherSA\dotnet.blazor.webassembly.weatherSA\Pages\Index.razor:76 
l.printErr @ blazor.webassembly.js:1
put_char @ dotnet.js:1
write @ dotnet.js:1
write @ dotnet.js:1
___syscall4 @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_wasm_invoke_method @ dotnet.js:1
call_method @ dotnet.js:1
(anonymous) @ dotnet.js:1
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
_mono_wasm_invoke_js_marshalled @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_wasm_invoke_method @ dotnet.js:1
call_method @ dotnet.js:1
set_task_result @ dotnet.js:1
(anonymous) @ dotnet.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.js:1
_mono_wasm_invoke_js_with_args @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_background_exec @ dotnet.js:1
pump_message @ dotnet.js:1
blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync () <0x1e635c0 + 0x0014c> in <filename unknown>:0 
l.printErr @ blazor.webassembly.js:1
put_char @ dotnet.js:1
write @ dotnet.js:1
write @ dotnet.js:1
___syscall4 @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_wasm_invoke_method @ dotnet.js:1
call_method @ dotnet.js:1
(anonymous) @ dotnet.js:1
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
_mono_wasm_invoke_js_marshalled @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_wasm_invoke_method @ dotnet.js:1
call_method @ dotnet.js:1
set_task_result @ dotnet.js:1
(anonymous) @ dotnet.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.js:1
_mono_wasm_invoke_js_with_args @ dotnet.js:1
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
(anonymous)
Module._mono_background_exec @ dotnet.js:1
pump_message @ dotnet.js:1
blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask (System.Threading.Tasks.Task taskToHandle) <0x2036138 + 0x000c2> in <filename unknown>:0 `

I'm using AspNetMonsters,Blazor.Geolocation::0.5.0-preview1 with Microsoft.AspNetCore.Blazor.Templates::3.2.0-preview1.20073.1

**Comment by ch200c** [comment]
It looks like you are missing the JavaScript file, here is a workaround: https://github.com/AspNetMonsters/Blazor.Geolocation/issues/10#issuecomment-536195860
